---
title: "Love Fades"
author: "DK"
date: "2024-09-30"
categories: [memory]
---

Someone once said, popular songs are about love or more specifically feelings of losing or remembering past love.

For my generation, those with both Korean and American heritage, there are many songs to choose from.

These line plus the way Toni Braxton sang these lyrics make this the instant classic

>...Come back and bring back my smile\
Come and take these tears away\
I need your arms to hold me now\
The nights are so unkind\
Bring back those nights when I held you beside me

>Un-break my heart\
Say you'll love me again\
Undo this hurt you caused\
When you walked out the door

For the traditional K-Pop, before dance was infused into song, this song was popular

그 사람 나를 보아도\
나는 그 사람을 몰라요\
두근거리는 마음은 아파도\
이젠 그대를 몰라요

그대 나를 알아도\
나는 기억을 못 합니다\
목이 메어와 눈물이 흘러도\
사랑이 지나가면

사랑이 지나가면

Even if that presence looks upon me,\
I no longer recognize it now.\
Though my heart still aches and trembles,\
I can no longer hold on to what I once knew.\
Even if you remember me,\
I can no longer recall those sacred memories.\
Even when my throat tightens and tears fall,\
When faith fades away.

That face I once longed to see,\
Now merely brushes past me in silence.\
In the emptiness of your gaze,\
I find no regret remains within me.\
Even if you call to me,\
I can no longer respond as I once did.\
Even when my heart breaks and tears flow,\
When faith fades away.

## Losing faith in others, society and God

These songs reflect the loss of something once deeply intimate, like faith, similar to how one might lose the memory of a past love. 

It conveys the idea of a once-powerful connection, now distant and unrecognizable, echoing both the loss of religious faith and the fading of past love. 

How do we regain that feeling?
How do we begin to replace it? Can it be replaced?

Or, once we leave our own "Garden of Eden" we can never return

Can it be that we have changed the most.
