---
title: "Love Fades"
author: "DK"
date: "2024-09-30"
categories: [memory]
---

황운학, 강현용

I have not met either one of my grandfathers.

One died when he was 36, 17 years before I was born.

The other lost contact with family when he was 40, presumably went North.

I am son of son of Hwang and Kang.

## Not Lonely

Always been lonely as refugees.

Always thought there will be some we can meet, beyond the northern border

No longer have that hope

In Korea, it was immediate siblings that came down since the war was supposed to last 3 months.

The war lasted 3 years but the armistice still drags on 71 years later.

This separation is biblical in length.

Jews were in bondage for around 120 years according to some scholars \[citation needed\]

Is this to purge out generations, like the return to the Promised Land

## Lonely Life in America

If life in South Korea was lonely, we became orphan like in America

Just our family.

Though my parents tried convinced others to join us, no takers.

No one was willing to migrate after turning 40 years of age.

Used to spending holidays alone.

Immigration happens, mainly for economic reasons, improvement in standing.

Carrying on their heritage
